### PR TITLE
Unneceessary allocations of TextView and view not updating on property changes #2

### PR DESCRIPTION
**Pull request by codedevote**
FIX: Only alllocate one TextView
IMPROVEMENTS: Update view when ChipText or BackgroundColor properties are changed

FIXES issue #2

### CODE REVIEW

**Comment by codedevote** [comment]
Would be great, if you could push a new nuget package, so I don't need to maintain my current private copy.

**Comment by yauhenipakala** [comment]
Hi @codedevote, thanks for your feedback and contribution!

Sorry for my long absence.

I checked your fix on Android API 19, and I have a problem - the text doesn't appear at the first.

Could you check your fix?

**Comment by codedevote** [comment]
I'll check with different API levels, just need to find some time to do it. I'll report back then.

**Comment by yauhenipakala** [comment]
Hi!
Fixed after sync with latest original library.

**Pull request closed without merging**
